Connect to the database

In [17]:
import sqlite3 

path = "D:/Data_Analysis/project/sale/csv/"  
db = path + 'BikeStore.db'
conn = sqlite3.connect(db)

In [18]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [19]:
%sql sqlite:///{db}

In [20]:
%sql SELECT name FROM sqlite_master WHERE type='table'

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[('brands',),
 ('categories',),
 ('customers',),
 ('order_items',),
 ('orders',),
 ('products',),
 ('staffs',),
 ('stocks',),
 ('stores',)]

In [ ]:
##

In [22]:
%%sql
SELECT store_id, p.product_name, MAX(quantity) FROM stocks s
JOIN products p
ON s.product_id = p.product_id
GROUP BY 1;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(1, 'Surly Ice Cream Truck Frameset - 2017', 30),
 (2, 'Electra Townie Original 7D - 2017', 30),
 (3, 'Surly Straggler 650b - 2016', 30)]

## what brand sale the most Cruisers Bicycles

In [23]:
%%sql
WITH Cruisers_b AS(
    SELECT * FROM products p
    JOIN categories c
    ON p.category_id = c.category_id
    WHERE category_name = "Cruisers Bicycles")

SELECT 
	b.brand_name, SUM(o.quantity)
FROM Cruisers_b cb
JOIN order_items o
ON cb.product_id = o.product_id
JOIN brands b
ON cb.brand_id = b.brand_id
GROUP BY 1
ORDER BY 2 DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[('Electra', 1329), ('Pure Cycles', 376), ('Sun Bicycles', 358)]

## what brand sale the most Mountain Bikes

In [24]:
%%sql
WITH Mountain_b AS(
	SELECT * FROM products p
	JOIN categories c
 	ON p.category_id = c.category_id
	WHERE category_name = "Mountain Bikes")

SELECT 
	b.brand_name, SUM(o.quantity)
FROM Mountain_b mb
JOIN order_items o
ON mb.product_id = o.product_id
JOIN brands b
ON mb.brand_id = b.brand_id
GROUP BY 1
ORDER BY 2 DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[('Trek', 752),
 ('Surly', 526),
 ('Haro', 195),
 ('Heller', 138),
 ('Ritchey', 118),
 ('Sun Bicycles', 26)]

## total sale by category bike

In [25]:
%%sql
SELECT 
    c.category_name,
    SUM(CASE 
			WHEN STRFTIME("%Y", o1.order_date) = '2016' THEN o2.quantity 
				ELSE 0 
		END
	) AS total_quantity_2016,
    SUM(CASE 
			WHEN STRFTIME("%Y", o1.order_date) = '2017' THEN o2.quantity 
				ELSE 0 
		END
	) AS total_quantity_2017,
    SUM(CASE 
			WHEN STRFTIME("%Y", o1.order_date) = '2018' THEN o2.quantity 
				ELSE 0 
		END
	) AS total_quantity_2018,
	SUM(o2.quantity) AS Total_quantity
FROM orders o1
JOIN order_items o2 ON o1.order_id = o2.order_id
JOIN products p
ON o2.product_id = p.product_id
JOIN categories c
ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY Total_quantity DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[('Cruisers Bicycles', 924, 814, 325, 2063),
 ('Mountain Bikes', 739, 764, 252, 1755),
 ('Children Bicycles', 350, 589, 240, 1179),
 ('Comfort Bicycles', 313, 373, 127, 813),
 ('Road Bikes', 0, 333, 226, 559),
 ('Cyclocross Bicycles', 233, 128, 33, 394),
 ('Electric Bikes', 104, 98, 113, 315)]

## what brand the most sale

In [26]:
%%sql
SELECT 
	b.brand_name , SUM(o.quantity)
FROM order_items o
JOIN products p
ON o.product_id = p.product_id
JOIN brands b
ON p.brand_id = b.brand_id
JOIN categories c
ON p.category_id = c.category_id
GROUP BY 1
ORDER BY 2 DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[('Electra', 2612),
 ('Trek', 1839),
 ('Surly', 908),
 ('Sun Bicycles', 731),
 ('Pure Cycles', 376),
 ('Haro', 331),
 ('Heller', 138),
 ('Ritchey', 118),
 ('Strider', 25)]

## what product is top sales

In [27]:
%%sql
SELECT 
	o.product_id, p.product_name, c.category_name, SUM(quantity) AS total_sale
FROM order_items o
JOIN products p
ON o.product_id = p.product_id
JOIN categories c
ON p.category_id = c.category_id
GROUP BY 1,2,3
ORDER BY 4 DESC
LIMIT 5;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(6, 'Surly Ice Cream Truck Frameset - 2016', 'Mountain Bikes', 167),
 (13, 'Electra Cruiser 1 (24-Inch) - 2016', 'Cruisers Bicycles', 157),
 (16, 'Electra Townie Original 7D EQ - 2016', 'Cruisers Bicycles', 156),
 (7, 'Trek Slash 8 27.5 - 2016', 'Mountain Bikes', 154),
 (23, "Electra Girl's Hawaii 1 (20-inch) - 2015/2016", 'Children Bicycles', 154)]

In [49]:
%%sql
SELECT 
	o.product_id, p.product_name, c.category_name, SUM(o.quantity) AS total_quantity,
    ROUND(SUM(o.list_price*o.quantity), 2) As total_sales, 
    ROUND(SUM((o.list_price*(1-o.discount)))*o.quantity, 2) AS total_sales_discount
FROM order_items o
JOIN products p
ON o.product_id = p.product_id
JOIN categories c
ON p.category_id = c.category_id
GROUP BY 1,2,3
ORDER BY 5 DESC
LIMIT 5;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(7, 'Trek Slash 8 27.5 - 2016', 'Mountain Bikes', 154, 615998.46, 727838.18),
 (9, 'Trek Conduit+ - 2016', 'Electric Bikes', 145, 434998.55, 542878.19),
 (4, 'Trek Fuel EX 8 29 - 2016', 'Mountain Bikes', 143, 414698.57, 249631.14),
 (11, 'Surly Straggler 650b - 2016', 'Cyclocross Bicycles', 151, 253829.49, 144951.77),
 (56, 'Trek Domane SLR 6 Disc - 2017', 'Road Bikes', 43, 236499.57, 137444.75)]

In [28]:
%%sql
SELECT customer_id, COUNT(*) AS order_count
FROM orders
GROUP BY customer_id
ORDER BY order_count DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(116, 3),
 (77, 3),
 (68, 3),
 (66, 3),
 (64, 3),
 (61, 3),
 (56, 3),
 (53, 3),
 (50, 3),
 (47, 3),
 (46, 3),
 (43, 3),
 (40, 3),
 (33, 3),
 (32, 3),
 (31, 3),
 (30, 3),
 (24, 3),
 (21, 3),
 (20, 3),
 (19, 3),
 (18, 3),
 (17, 3),
 (16, 3),
 (15, 3),
 (14, 3),
 (13, 3),
 (12, 3),
 (11, 3),
 (10, 3),
 (9, 3),
 (8, 3),
 (7, 3),
 (6, 3),
 (5, 3),
 (4, 3),
 (3, 3),
 (2, 3),
 (1, 3),
 (240, 2),
 (239, 2),
 (237, 2),
 (233, 2),
 (231, 2),
 (224, 2),
 (217, 2),
 (208, 2),
 (194, 2),
 (192, 2),
 (191, 2),
 (188, 2),
 (187, 2),
 (181, 2),
 (176, 2),
 (175, 2),
 (172, 2),
 (170, 2),
 (169, 2),
 (165, 2),
 (157, 2),
 (153, 2),
 (151, 2),
 (138, 2),
 (136, 2),
 (135, 2),
 (124, 2),
 (123, 2),
 (121, 2),
 (120, 2),
 (119, 2),
 (117, 2),
 (110, 2),
 (109, 2),
 (104, 2),
 (97, 2),
 (94, 2),
 (93, 2),
 (92, 2),
 (91, 2),
 (90, 2),
 (89, 2),
 (88, 2),
 (87, 2),
 (86, 2),
 (85, 2),
 (84, 2),
 (83, 2),
 (82, 2),
 (81, 2),
 (80, 2),
 (79, 2),
 (78, 2),
 (76, 2),
 (75, 2),
 (74, 2),
 (73, 2),
 (72, 2),
 (71, 2),
 (70, 2),
 (69, 2),
 (67, 2),
 (65, 2),
 (63, 2),
 (62, 2),
 (60, 2),
 (59, 2),
 (58, 2),
 (57, 2),
 (55, 2),
 (54, 2),
 (52, 2),
 (51, 2),
 (49, 2),
 (48, 2),
 (45, 2),
 (44, 2),
 (42, 2),
 (41, 2),
 (39, 2),
 (38, 2),
 (37, 2),
 (36, 2),
 (35, 2),
 (34, 2),
 (29, 2),
 (28, 2),
 (27, 2),
 (26, 2),
 (25, 2),
 (23, 2),
 (22, 2),
 (1445, 1),
 (1444, 1),
 (1443, 1),
 (1442, 1),
 (1441, 1),
 (1440, 1),
 (1439, 1),
 (1438, 1),
 (1437, 1),
 (1436, 1),
 (1435, 1),
 (1434, 1),
 (1433, 1),
 (1432, 1),
 (1431, 1),
 (1430, 1),
 (1429, 1),
 (1428, 1),
 (1427, 1),
 (1426, 1),
 (1425, 1),
 (1424, 1),
 (1423, 1),
 (1422, 1),
 (1421, 1),
 (1420, 1),
 (1419, 1),
 (1418, 1),
 (1417, 1),
 (1416, 1),
 (1415, 1),
 (1414, 1),
 (1413, 1),
 (1412, 1),
 (1411, 1),
 (1410, 1),
 (1409, 1),
 (1408, 1),
 (1407, 1),
 (1406, 1),
 (1405, 1),
 (1404, 1),
 (1403, 1),
 (1402, 1),
 (1401, 1),
 (1400, 1),
 (1399, 1),
 (1398, 1),
 (1397, 1),
 (1396, 1),
 (1395, 1),
 (1394, 1),
 (1393, 1),
 (1392, 1),
 (1391, 1),
 (1390, 1),
 (1389, 1),
 (1388, 1),
 (1387, 1),
 (1386, 1),
 (1385, 1),
 (1384, 1),
 (1383, 1),
 (1382, 1),
 (1381, 1),
 (1380, 1),
 (1379, 1),
 (1378, 1),
 (1377, 1),
 (1376, 1),
 (1375, 1),
 (1374, 1),
 (1373, 1),
 (1372, 1),
 (1371, 1),
 (1370, 1),
 (1369, 1),
 (1368, 1),
 (1367, 1),
 (1366, 1),
 (1365, 1),
 (1364, 1),
 (1363, 1),
 (1362, 1),
 (1361, 1),
 (1360, 1),
 (1359, 1),
 (1358, 1),
 (1357, 1),
 (1356, 1),
 (1355, 1),
 (1354, 1),
 (1353, 1),
 (1352, 1),
 (1351, 1),
 (1350, 1),
 (1349, 1),
 (1348, 1),
 (1347, 1),
 (1346, 1),
 (1345, 1),
 (1344, 1),
 (1343, 1),
 (1342, 1),
 (1341, 1),
 (1340, 1),
 (1339, 1),
 (1338, 1),
 (1337, 1),
 (1336, 1),
 (1335, 1),
 (1334, 1),
 (1333, 1),
 (1332, 1),
 (1331, 1),
 (1330, 1),
 (1329, 1),
 (1328, 1),
 (1327, 1),
 (1326, 1),
 (1325, 1),
 (1324, 1),
 (1323, 1),
 (1322, 1),
 (1321, 1),
 (1320, 1),
 (1319, 1),
 (1318, 1),
 (1317, 1),
 (1316, 1),
 (1315, 1),
 (1314, 1),
 (1313, 1),
 (1312, 1),
 (1311, 1),
 (1310, 1),
 (1309, 1),
 (1308, 1),
 (1307, 1),
 (1306, 1),
 (1305, 1),
 (1304, 1),
 (1303, 1),
 (1302, 1),
 (1301, 1),
 (1300, 1),
 (1299, 1),
 (1298, 1),
 (1297, 1),
 (1296, 1),
 (1295, 1),
 (1294, 1),
 (1293, 1),
 (1292, 1),
 (1291, 1),
 (1290, 1),
 (1289, 1),
 (1288, 1),
 (1287, 1),
 (1286, 1),
 (1285, 1),
 (1284, 1),
 (1283, 1),
 (1282, 1),
 (1281, 1),
 (1280, 1),
 (1279, 1),
 (1278, 1),
 (1277, 1),
 (1276, 1),
 (1275, 1),
 (1274, 1),
 (1273, 1),
 (1272, 1),
 (1271, 1),
 (1270, 1),
 (1269, 1),
 (1268, 1),
 (1267, 1),
 (1266, 1),
 (1265, 1),
 (1264, 1),
 (1263, 1),
 (1262, 1),
 (1261, 1),
 (1260, 1),
 (1259, 1),
 (1258, 1),
 (1257, 1),
 (1256, 1),
 (1255, 1),
 (1254, 1),
 (1253, 1),
 (1252, 1),
 (1251, 1),
 (1250, 1),
 (1249, 1),
 (1248, 1),
 (1247, 1),
 (1246, 1),
 (1245, 1),
 (1244, 1),
 (1243, 1),
 (1242, 1),
 (1241, 1),
 (1240, 1),
 (1239, 1),
 (1238, 1),
 (1237, 1),
 (1236, 1),
 (1235, 1),
 (1234, 1),
 (1233, 1),
 (1232, 1),
 (1231, 1),
 (1230, 1),
 (1229, 1),
 (1228, 1),
 (1227, 1),
 (1226, 1),
 (1225, 1),
 (1224, 1),
 (1223, 1),
 (1222, 1),
 (1221, 1),
 (1220, 1),
 (1219, 1),
 (1218, 1),
 (1217, 1),
 (1216, 1),
 (1215, 1),
 (1214, 1),
 (1213, 1),
 (1212, 1),
 (1211, 1),
 (1210, 1),
 (1209, 1),
 (1208, 1),
 (1207, 1),
 (1206, 1),
 (1205, 1),
 (1204, 1),
 (1203, 1),
 (1202, 1),
 (1201, 1),
 (1200, 1),
 (1199, 1),
 (1198, 1),
 (1197, 1),
 (1196, 1),
 (1195, 1),
 (1194, 1),
 (1193, 1),
 (1192, 1),
 (1191, 1),
 (1190, 1),
 (1189, 1),
 (1188, 1),
 (1187, 1),
 (1186, 1),
 (1185, 1),
 (1184, 1),
 (1183, 1),
 (1182, 1),
 (1181, 1),
 (1180, 1),
 (1179, 1),
 (1178, 1),
 (1177, 1),
 (1176, 1),
 (1175, 1),
 (1174, 1),
 (1173, 1),
 (1172, 1),
 (1171, 1),
 (1170, 1),
 (1169, 1),
 (1168, 1),
 (1167, 1),
 (1166, 1),
 (1165, 1),
 (1164, 1),
 (1163, 1),
 (1162, 1),
 (1161, 1),
 (1160, 1),
 (1159, 1),
 (1158, 1),
 (1157, 1),
 (1156, 1),
 (1155, 1),
 (1154, 1),
 (1153, 1),
 (1152, 1),
 (1151, 1),
 (1150, 1),
 (1149, 1),
 (1148, 1),
 (1147, 1),
 (1146, 1),
 (1145, 1),
 (1144, 1),
 (1143, 1),
 (1142, 1),
 (1141, 1),
 (1140, 1),
 (1139, 1),
 (1138, 1),
 (1137, 1),
 (1136, 1),
 (1135, 1),
 (1134, 1),
 (1133, 1),
 (1132, 1),
 (1131, 1),
 (1130, 1),
 (1129, 1),
 (1128, 1),
 (1127, 1),
 (1126, 1),
 (1125, 1),
 (1124, 1),
 (1123, 1),
 (1122, 1),
 (1121, 1),
 (1120, 1),
 (1119, 1),
 (1118, 1),
 (1117, 1),
 (1116, 1),
 (1115, 1),
 (1114, 1),
 (1113, 1),
 (1112, 1),
 (1111, 1),
 (1110, 1),
 (1109, 1),
 (1108, 1),
 (1107, 1),
 (1106, 1),
 (1105, 1),
 (1104, 1),
 (1103, 1),
 (1102, 1),
 (1101, 1),
 (1100, 1),
 (1099, 1),
 (1098, 1),
 (1097, 1),
 (1096, 1),
 (1095, 1),
 (1094, 1),
 (1093, 1),
 (1092, 1),
 (1091, 1),
 (1090, 1),
 (1089, 1),
 (1088, 1),
 (1087, 1),
 (1086, 1),
 (1085, 1),
 (1084, 1),
 (1083, 1),
 (1082, 1),
 (1081, 1),
 (1080, 1),
 (1079, 1),
 (1078, 1),
 (1077, 1),
 (1076, 1),
 (1075, 1),
 (1074, 1),
 (1073, 1),
 (1072, 1),
 (1071, 1),
 (1070, 1),
 (1069, 1),
 (1068, 1),
 (1067, 1),
 (1066, 1),
 (1065, 1),
 (1064, 1),
 (1063, 1),
 (1062, 1),
 (1061, 1),
 (1060, 1),
 (1059, 1),
 (1058, 1),
 (1057, 1),
 (1056, 1),
 (1055, 1),
 (1054, 1),
 (1053, 1),
 (1052, 1),
 (1051, 1),
 (1050, 1),
 (1049, 1),
 (1048, 1),
 (1047, 1),
 (1046, 1),
 (1045, 1),
 (1044, 1),
 (1043, 1),
 (1042, 1),
 (1041, 1),
 (1040, 1),
 (1039, 1),
 (1038, 1),
 (1037, 1),
 (1036, 1),
 (1035, 1),
 (1034, 1),
 (1033, 1),
 (1032, 1),
 (1031, 1),
 (1030, 1),
 (1029, 1),
 (1028, 1),
 (1027, 1),
 (1026, 1),
 (1025, 1),
 (1024, 1),
 (1023, 1),
 (1022, 1),
 (1021, 1),
 (1020, 1),
 (1019, 1),
 (1018, 1),
 (1017, 1),
 (1016, 1),
 (1015, 1),
 (1014, 1),
 (1013, 1),
 (1012, 1),
 (1011, 1),
 (1010, 1),
 (1009, 1),
 (1008, 1),
 (1007, 1),
 (1006, 1),
 (1005, 1),
 (1004, 1),
 (1003, 1),
 (1002, 1),
 (1001, 1),
 (1000, 1),
 (999, 1),
 (998, 1),
 (997, 1),
 (996, 1),
 (995, 1),
 (994, 1),
 (993, 1),
 (992, 1),
 (991, 1),
 (990, 1),
 (989, 1),
 (988, 1),
 (987, 1),
 (986, 1),
 (985, 1),
 (984, 1),
 (983, 1),
 (982, 1),
 (981, 1),
 (980, 1),
 (979, 1),
 (978, 1),
 (977, 1),
 (976, 1),
 (975, 1),
 (974, 1),
 (973, 1),
 (972, 1),
 (971, 1),
 (970, 1),
 (969, 1),
 (968, 1),
 (967, 1),
 (966, 1),
 (965, 1),
 (964, 1),
 (963, 1),
 (962, 1),
 (961, 1),
 (960, 1),
 (959, 1),
 (958, 1),
 (957, 1),
 (956, 1),
 (955, 1),
 (954, 1),
 (953, 1),
 (952, 1),
 (951, 1),
 (950, 1),
 (949, 1),
 (948, 1),
 (947, 1),
 (946, 1),
 (945, 1),
 (944, 1),
 (943, 1),
 (942, 1),
 (941, 1),
 (940, 1),
 (939, 1),
 (938, 1),
 (937, 1),
 (936, 1),
 (935, 1),
 (934, 1),
 (933, 1),
 (932, 1),
 (931, 1),
 (930, 1),
 (929, 1),
 (928, 1),
 (927, 1),
 (926, 1),
 (925, 1),
 (924, 1),
 (923, 1),
 (922, 1),
 (921, 1),
 (920, 1),
 (919, 1),
 (918, 1),
 (917, 1),
 (916, 1),
 (915, 1),
 (914, 1),
 (913, 1),
 (912, 1),
 (911, 1),
 (910, 1),
 (909, 1),
 (908, 1),
 (907, 1),
 (906, 1),
 (905, 1),
 (904, 1),
 (903, 1),
 (902, 1),
 (901, 1),
 (900, 1),
 (899, 1),
 (898, 1),
 (897, 1),
 (896, 1),
 (895, 1),
 (894, 1),
 (893, 1),
 (892, 1),
 (891, 1),
 (890, 1),
 (889, 1),
 (888, 1),
 (887, 1),
 (886, 1),
 (885, 1),
 (884, 1),
 (883, 1),
 (882, 1),
 (881, 1),
 (880, 1),
 (879, 1),
 (878, 1),
 (877, 1),
 (876, 1),
 (875, 1),
 (874, 1),
 (873, 1),
 (872, 1),
 (871, 1),
 (870, 1),
 (869, 1),
 (868, 1),
 (867, 1),
 (866, 1),
 (865, 1),
 (864, 1),
 (863, 1),
 (862, 1),
 (861, 1),
 (860, 1),
 (859, 1),
 (858, 1),
 (857, 1),
 (856, 1),
 (855, 1),
 (854, 1),
 (853, 1),
 (852, 1),
 (851, 1),
 (850, 1),
 (849, 1),
 (848, 1),
 (847, 1),
 (846, 1),
 (845, 1),
 (844, 1),
 (843, 1),
 (842, 1),
 (841, 1),
 (840, 1),
 (839, 1),
 (838, 1),
 (837, 1),
 (836, 1),
 (835, 1),
 (834, 1),
 (833, 1),
 (832, 1),
 (831, 1),
 (830, 1),
 (829, 1),
 (828, 1),
 (827, 1),
 (826, 1),
 (825, 1),
 (824, 1),
 (823, 1),
 (822, 1),
 (821, 1),
 (820, 1),
 (819, 1),
 (818, 1),
 (817, 1),
 (816, 1),
 (815, 1),
 (814, 1),
 (813, 1),
 (812, 1),
 (811, 1),
 (810, 1),
 (809, 1),
 (808, 1),
 (807, 1),
 (806, 1),
 (805, 1),
 (804, 1),
 (803, 1),
 (802, 1),
 (801, 1),
 (800, 1),
 (799, 1),
 (798, 1),
 (797, 1),
 (796, 1),
 (795, 1),
 (794, 1),
 (793, 1),
 (792, 1),
 (791, 1),
 (790, 1),
 (789, 1),
 (788, 1),
 (787, 1),
 (786, 1),
 (785, 1),
 (784, 1),
 (783, 1),
 (782, 1),
 (781, 1),
 (780, 1),
 (779, 1),
 (778, 1),
 (777, 1),
 (776, 1),
 (775, 1),
 (774, 1),
 (773, 1),
 (772, 1),
 (771, 1),
 (770, 1),
 (769, 1),
 (768, 1),
 (767, 1),
 (766, 1),
 (765, 1),
 (764, 1),
 (763, 1),
 (762, 1),
 (761, 1),
 (760, 1),
 (759, 1),
 (758, 1),
 (757, 1),
 (756, 1),
 (755, 1),
 (754, 1),
 (753, 1),
 (752, 1),
 (751, 1),
 (750, 1),
 (749, 1),
 (748, 1),
 (747, 1),
 (746, 1),
 (745, 1),
 (744, 1),
 (743, 1),
 (742, 1),
 (741, 1),
 (740, 1),
 (739, 1),
 (738, 1),
 (737, 1),
 (736, 1),
 (735, 1),
 (734, 1),
 (733, 1),
 (732, 1),
 (731, 1),
 (730, 1),
 (729, 1),
 (728, 1),
 (727, 1),
 (726, 1),
 (725, 1),
 (724, 1),
 (723, 1),
 (722, 1),
 (721, 1),
 (720, 1),
 (719, 1),
 (718, 1),
 (717, 1),
 (716, 1),
 (715, 1),
 (714, 1),
 (713, 1),
 (712, 1),
 (711, 1),
 (710, 1),
 (709, 1),
 (708, 1),
 (707, 1),
 (706, 1),
 (705, 1),
 (704, 1),
 (703, 1),
 (702, 1),
 (701, 1),
 (700, 1),
 (699, 1),
 (698, 1),
 (697, 1),
 (696, 1),
 (695, 1),
 (694, 1),
 (693, 1),
 (692, 1),
 (691, 1),
 (690, 1),
 (689, 1),
 (688, 1),
 (687, 1),
 (686, 1),
 (685, 1),
 (684, 1),
 (683, 1),
 (682, 1),
 (681, 1),
 (680, 1),
 (679, 1),
 (678, 1),
 (677, 1),
 (676, 1),
 (675, 1),
 (674, 1),
 (673, 1),
 (672, 1),
 (671, 1),
 (670, 1),
 (669, 1),
 (668, 1),
 (667, 1),
 (666, 1),
 (665, 1),
 (664, 1),
 (663, 1),
 (662, 1),
 (661, 1),
 (660, 1),
 (659, 1),
 (658, 1),
 (657, 1),
 (656, 1),
 (655, 1),
 (654, 1),
 (653, 1),
 (652, 1),
 (651, 1),
 (650, 1),
 (649, 1),
 (648, 1),
 (647, 1),
 (646, 1),
 (645, 1),
 (644, 1),
 (643, 1),
 (642, 1),
 (641, 1),
 (640, 1),
 (639, 1),
 (638, 1),
 (637, 1),
 (636, 1),
 (635, 1),
 (634, 1),
 (633, 1),
 (632, 1),
 (631, 1),
 (630, 1),
 (629, 1),
 (628, 1),
 (627, 1),
 (626, 1),
 (625, 1),
 (624, 1),
 (623, 1),
 (622, 1),
 (621, 1),
 (620, 1),
 (619, 1),
 (618, 1),
 (617, 1),
 (616, 1),
 (615, 1),
 (614, 1),
 (613, 1),
 (612, 1),
 (611, 1),
 (610, 1),
 (609, 1),
 (608, 1),
 (607, 1),
 (606, 1),
 (605, 1),
 (604, 1),
 (603, 1),
 (602, 1),
 (601, 1),
 (600, 1),
 (599, 1),
 (598, 1),
 (597, 1),
 (596, 1),
 (595, 1),
 (594, 1),
 (593, 1),
 (592, 1),
 (591, 1),
 (590, 1),
 (589, 1),
 (588, 1),
 (587, 1),
 (586, 1),
 (585, 1),
 (584, 1),
 (583, 1),
 (582, 1),
 (581, 1),
 (580, 1),
 (579, 1),
 (578, 1),
 (577, 1),
 ...]

In [29]:
%%sql
SELECT order_id, COUNT(*) AS order_count
FROM order_items
GROUP BY order_id
ORDER BY order_count DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(1612, 5),
 (1605, 5),
 (1601, 5),
 (1593, 5),
 (1592, 5),
 (1591, 5),
 (1586, 5),
 (1585, 5),
 (1584, 5),
 (1577, 5),
 (1575, 5),
 (1573, 5),
 (1565, 5),
 (1558, 5),
 (1556, 5),
 (1555, 5),
 (1550, 5),
 (1543, 5),
 (1542, 5),
 (1541, 5),
 (1540, 5),
 (1538, 5),
 (1533, 5),
 (1519, 5),
 (1516, 5),
 (1515, 5),
 (1511, 5),
 (1510, 5),
 (1507, 5),
 (1502, 5),
 (1501, 5),
 (1499, 5),
 (1496, 5),
 (1487, 5),
 (1482, 5),
 (1476, 5),
 (1462, 5),
 (1460, 5),
 (1456, 5),
 (1450, 5),
 (1449, 5),
 (1440, 5),
 (1438, 5),
 (1428, 5),
 (1425, 5),
 (1409, 5),
 (1397, 5),
 (1390, 5),
 (1382, 5),
 (1378, 5),
 (1352, 5),
 (1350, 5),
 (1346, 5),
 (1343, 5),
 (1336, 5),
 (1334, 5),
 (1333, 5),
 (1330, 5),
 (1329, 5),
 (1328, 5),
 (1315, 5),
 (1308, 5),
 (1306, 5),
 (1303, 5),
 (1283, 5),
 (1277, 5),
 (1276, 5),
 (1257, 5),
 (1255, 5),
 (1240, 5),
 (1237, 5),
 (1227, 5),
 (1226, 5),
 (1221, 5),
 (1216, 5),
 (1214, 5),
 (1211, 5),
 (1210, 5),
 (1208, 5),
 (1205, 5),
 (1201, 5),
 (1175, 5),
 (1168, 5),
 (1162, 5),
 (1149, 5),
 (1142, 5),
 (1139, 5),
 (1125, 5),
 (1124, 5),
 (1122, 5),
 (1120, 5),
 (1112, 5),
 (1097, 5),
 (1095, 5),
 (1087, 5),
 (1086, 5),
 (1084, 5),
 (1080, 5),
 (1078, 5),
 (1055, 5),
 (1053, 5),
 (1049, 5),
 (1046, 5),
 (1040, 5),
 (1037, 5),
 (1036, 5),
 (1028, 5),
 (1025, 5),
 (1024, 5),
 (1020, 5),
 (1017, 5),
 (1007, 5),
 (1006, 5),
 (993, 5),
 (992, 5),
 (989, 5),
 (983, 5),
 (981, 5),
 (971, 5),
 (957, 5),
 (956, 5),
 (955, 5),
 (948, 5),
 (946, 5),
 (945, 5),
 (944, 5),
 (942, 5),
 (937, 5),
 (934, 5),
 (930, 5),
 (927, 5),
 (906, 5),
 (900, 5),
 (890, 5),
 (884, 5),
 (880, 5),
 (869, 5),
 (860, 5),
 (859, 5),
 (853, 5),
 (846, 5),
 (845, 5),
 (844, 5),
 (841, 5),
 (813, 5),
 (807, 5),
 (806, 5),
 (805, 5),
 (800, 5),
 (799, 5),
 (798, 5),
 (797, 5),
 (792, 5),
 (779, 5),
 (774, 5),
 (765, 5),
 (758, 5),
 (754, 5),
 (753, 5),
 (749, 5),
 (740, 5),
 (712, 5),
 (710, 5),
 (699, 5),
 (694, 5),
 (686, 5),
 (685, 5),
 (681, 5),
 (677, 5),
 (671, 5),
 (667, 5),
 (664, 5),
 (663, 5),
 (662, 5),
 (653, 5),
 (652, 5),
 (645, 5),
 (640, 5),
 (632, 5),
 (629, 5),
 (610, 5),
 (595, 5),
 (590, 5),
 (584, 5),
 (580, 5),
 (574, 5),
 (570, 5),
 (558, 5),
 (552, 5),
 (549, 5),
 (524, 5),
 (519, 5),
 (518, 5),
 (479, 5),
 (467, 5),
 (466, 5),
 (461, 5),
 (458, 5),
 (444, 5),
 (434, 5),
 (431, 5),
 (430, 5),
 (429, 5),
 (421, 5),
 (389, 5),
 (384, 5),
 (383, 5),
 (373, 5),
 (346, 5),
 (340, 5),
 (338, 5),
 (329, 5),
 (324, 5),
 (316, 5),
 (298, 5),
 (267, 5),
 (238, 5),
 (234, 5),
 (228, 5),
 (223, 5),
 (208, 5),
 (198, 5),
 (196, 5),
 (195, 5),
 (192, 5),
 (191, 5),
 (179, 5),
 (169, 5),
 (146, 5),
 (121, 5),
 (120, 5),
 (118, 5),
 (113, 5),
 (103, 5),
 (100, 5),
 (99, 5),
 (93, 5),
 (73, 5),
 (67, 5),
 (38, 5),
 (35, 5),
 (30, 5),
 (29, 5),
 (25, 5),
 (18, 5),
 (6, 5),
 (1, 5),
 (1609, 4),
 (1602, 4),
 (1587, 4),
 (1579, 4),
 (1572, 4),
 (1559, 4),
 (1553, 4),
 (1549, 4),
 (1546, 4),
 (1534, 4),
 (1526, 4),
 (1524, 4),
 (1521, 4),
 (1520, 4),
 (1508, 4),
 (1491, 4),
 (1486, 4),
 (1480, 4),
 (1475, 4),
 (1469, 4),
 (1466, 4),
 (1464, 4),
 (1458, 4),
 (1457, 4),
 (1454, 4),
 (1452, 4),
 (1439, 4),
 (1435, 4),
 (1434, 4),
 (1431, 4),
 (1423, 4),
 (1415, 4),
 (1408, 4),
 (1407, 4),
 (1402, 4),
 (1400, 4),
 (1399, 4),
 (1395, 4),
 (1393, 4),
 (1386, 4),
 (1385, 4),
 (1384, 4),
 (1377, 4),
 (1370, 4),
 (1367, 4),
 (1364, 4),
 (1355, 4),
 (1353, 4),
 (1349, 4),
 (1348, 4),
 (1345, 4),
 (1344, 4),
 (1341, 4),
 (1332, 4),
 (1331, 4),
 (1327, 4),
 (1325, 4),
 (1324, 4),
 (1318, 4),
 (1311, 4),
 (1310, 4),
 (1305, 4),
 (1304, 4),
 (1299, 4),
 (1296, 4),
 (1288, 4),
 (1287, 4),
 (1285, 4),
 (1280, 4),
 (1271, 4),
 (1268, 4),
 (1267, 4),
 (1264, 4),
 (1262, 4),
 (1261, 4),
 (1250, 4),
 (1248, 4),
 (1244, 4),
 (1242, 4),
 (1239, 4),
 (1238, 4),
 (1224, 4),
 (1213, 4),
 (1212, 4),
 (1197, 4),
 (1194, 4),
 (1187, 4),
 (1186, 4),
 (1185, 4),
 (1179, 4),
 (1178, 4),
 (1173, 4),
 (1169, 4),
 (1164, 4),
 (1161, 4),
 (1157, 4),
 (1155, 4),
 (1150, 4),
 (1148, 4),
 (1140, 4),
 (1137, 4),
 (1133, 4),
 (1132, 4),
 (1118, 4),
 (1115, 4),
 (1111, 4),
 (1104, 4),
 (1099, 4),
 (1094, 4),
 (1092, 4),
 (1088, 4),
 (1083, 4),
 (1068, 4),
 (1067, 4),
 (1062, 4),
 (1060, 4),
 (1050, 4),
 (1047, 4),
 (1034, 4),
 (1029, 4),
 (1022, 4),
 (1019, 4),
 (1015, 4),
 (1014, 4),
 (1011, 4),
 (1002, 4),
 (1001, 4),
 (1000, 4),
 (990, 4),
 (984, 4),
 (982, 4),
 (979, 4),
 (977, 4),
 (973, 4),
 (970, 4),
 (967, 4),
 (960, 4),
 (959, 4),
 (935, 4),
 (920, 4),
 (915, 4),
 (914, 4),
 (912, 4),
 (911, 4),
 (905, 4),
 (904, 4),
 (902, 4),
 (898, 4),
 (892, 4),
 (891, 4),
 (881, 4),
 (879, 4),
 (878, 4),
 (876, 4),
 (875, 4),
 (874, 4),
 (871, 4),
 (866, 4),
 (858, 4),
 (848, 4),
 (843, 4),
 (838, 4),
 (832, 4),
 (827, 4),
 (821, 4),
 (818, 4),
 (815, 4),
 (814, 4),
 (811, 4),
 (810, 4),
 (808, 4),
 (803, 4),
 (802, 4),
 (794, 4),
 (783, 4),
 (782, 4),
 (776, 4),
 (773, 4),
 (770, 4),
 (767, 4),
 (748, 4),
 (747, 4),
 (741, 4),
 (738, 4),
 (737, 4),
 (734, 4),
 (731, 4),
 (730, 4),
 (728, 4),
 (725, 4),
 (724, 4),
 (721, 4),
 (716, 4),
 (713, 4),
 (707, 4),
 (703, 4),
 (693, 4),
 (692, 4),
 (691, 4),
 (690, 4),
 (687, 4),
 (676, 4),
 (675, 4),
 (673, 4),
 (670, 4),
 (660, 4),
 (659, 4),
 (654, 4),
 (651, 4),
 (649, 4),
 (646, 4),
 (639, 4),
 (633, 4),
 (630, 4),
 (625, 4),
 (624, 4),
 (622, 4),
 (615, 4),
 (612, 4),
 (609, 4),
 (605, 4),
 (599, 4),
 (587, 4),
 (585, 4),
 (578, 4),
 (566, 4),
 (565, 4),
 (561, 4),
 (551, 4),
 (545, 4),
 (542, 4),
 (537, 4),
 (536, 4),
 (534, 4),
 (533, 4),
 (527, 4),
 (526, 4),
 (523, 4),
 (515, 4),
 (508, 4),
 (501, 4),
 (499, 4),
 (490, 4),
 (484, 4),
 (476, 4),
 (468, 4),
 (460, 4),
 (457, 4),
 (452, 4),
 (449, 4),
 (438, 4),
 (433, 4),
 (423, 4),
 (415, 4),
 (408, 4),
 (403, 4),
 (398, 4),
 (388, 4),
 (375, 4),
 (368, 4),
 (363, 4),
 (360, 4),
 (358, 4),
 (357, 4),
 (351, 4),
 (343, 4),
 (321, 4),
 (319, 4),
 (317, 4),
 (314, 4),
 (310, 4),
 (300, 4),
 (296, 4),
 (294, 4),
 (287, 4),
 (286, 4),
 (282, 4),
 (278, 4),
 (271, 4),
 (269, 4),
 (264, 4),
 (259, 4),
 (258, 4),
 (257, 4),
 (255, 4),
 (248, 4),
 (240, 4),
 (239, 4),
 (237, 4),
 (233, 4),
 (232, 4),
 (224, 4),
 (220, 4),
 (212, 4),
 (207, 4),
 (203, 4),
 (202, 4),
 (201, 4),
 (183, 4),
 (181, 4),
 (178, 4),
 (175, 4),
 (170, 4),
 (168, 4),
 (167, 4),
 (160, 4),
 (150, 4),
 (140, 4),
 (135, 4),
 (128, 4),
 (117, 4),
 (112, 4),
 (98, 4),
 (97, 4),
 (95, 4),
 (94, 4),
 (91, 4),
 (86, 4),
 (79, 4),
 (78, 4),
 (77, 4),
 (64, 4),
 (60, 4),
 (53, 4),
 (48, 4),
 (47, 4),
 (39, 4),
 (28, 4),
 (27, 4),
 (26, 4),
 (17, 4),
 (16, 4),
 (15, 4),
 (13, 4),
 (1615, 3),
 (1614, 3),
 (1611, 3),
 (1600, 3),
 (1598, 3),
 (1590, 3),
 (1589, 3),
 (1578, 3),
 (1576, 3),
 (1571, 3),
 (1568, 3),
 (1562, 3),
 (1548, 3),
 (1536, 3),
 (1527, 3),
 (1525, 3),
 (1522, 3),
 (1518, 3),
 (1513, 3),
 (1506, 3),
 (1505, 3),
 (1497, 3),
 (1495, 3),
 (1494, 3),
 (1490, 3),
 (1489, 3),
 (1484, 3),
 (1470, 3),
 (1468, 3),
 (1467, 3),
 (1446, 3),
 (1445, 3),
 (1443, 3),
 (1442, 3),
 (1441, 3),
 (1427, 3),
 (1426, 3),
 (1422, 3),
 (1420, 3),
 (1419, 3),
 (1416, 3),
 (1412, 3),
 (1410, 3),
 (1404, 3),
 (1401, 3),
 (1391, 3),
 (1389, 3),
 (1379, 3),
 (1368, 3),
 (1366, 3),
 (1365, 3),
 (1362, 3),
 (1361, 3),
 (1357, 3),
 (1356, 3),
 (1340, 3),
 (1323, 3),
 (1321, 3),
 (1320, 3),
 (1314, 3),
 (1313, 3),
 (1312, 3),
 (1307, 3),
 (1302, 3),
 (1301, 3),
 (1297, 3),
 (1295, 3),
 (1293, 3),
 (1290, 3),
 (1286, 3),
 (1284, 3),
 (1281, 3),
 (1273, 3),
 (1272, 3),
 (1269, 3),
 (1263, 3),
 (1253, 3),
 (1252, 3),
 (1251, 3),
 (1249, 3),
 (1247, 3),
 (1246, 3),
 (1236, 3),
 (1233, 3),
 (1232, 3),
 (1228, 3),
 (1225, 3),
 (1220, 3),
 (1219, 3),
 (1207, 3),
 (1199, 3),
 (1192, 3),
 (1191, 3),
 (1189, 3),
 (1188, 3),
 (1183, 3),
 (1174, 3),
 (1171, 3),
 (1170, 3),
 (1167, 3),
 (1154, 3),
 (1152, 3),
 (1146, 3),
 (1143, 3),
 (1138, 3),
 (1129, 3),
 (1128, 3),
 (1127, 3),
 (1126, 3),
 (1119, 3),
 (1117, 3),
 (1108, 3),
 (1105, 3),
 (1093, 3),
 (1091, 3),
 (1085, 3),
 (1076, 3),
 (1074, 3),
 (1073, 3),
 (1072, 3),
 (1070, 3),
 (1066, 3),
 (1065, 3),
 (1063, 3),
 (1059, 3),
 (1058, 3),
 (1057, 3),
 (1052, 3),
 (1048, 3),
 (1041, 3),
 (1033, 3),
 (1030, 3),
 (1018, 3),
 (1008, 3),
 (1005, 3),
 (997, 3),
 (995, 3),
 (994, 3),
 (991, 3),
 (988, 3),
 (987, 3),
 (986, 3),
 (985, 3),
 (980, 3),
 (978, 3),
 (968, 3),
 (961, 3),
 (951, 3),
 (947, 3),
 (941, 3),
 (933, 3),
 (929, 3),
 (922, 3),
 (921, 3),
 (918, 3),
 (908, 3),
 (899, 3),
 (882, 3),
 (864, 3),
 (862, 3),
 (855, 3),
 (850, 3),
 (840, 3),
 (839, 3),
 (837, 3),
 (835, 3),
 (834, 3),
 (831, 3),
 (830, 3),
 (828, 3),
 (823, 3),
 (817, 3),
 (809, 3),
 (804, 3),
 (793, 3),
 (788, 3),
 (785, 3),
 (784, 3),
 (781, 3),
 (777, 3),
 (769, 3),
 (764, 3),
 (755, 3),
 (745, 3),
 (736, 3),
 (733, 3),
 (723, 3),
 (722, 3),
 (718, 3),
 (711, 3),
 (709, 3),
 (708, 3),
 (706, 3),
 (704, 3),
 (702, 3),
 (698, 3),
 (696, 3),
 (682, 3),
 (680, 3),
 (672, 3),
 (665, 3),
 (658, 3),
 (656, 3),
 (641, 3),
 (638, 3),
 (627, 3),
 (613, 3),
 (608, 3),
 (607, 3),
 (600, 3),
 (598, 3),
 (596, 3),
 (592, 3),
 (591, 3),
 (572, 3),
 (563, 3),
 (559, 3),
 (555, 3),
 (554, 3),
 (553, 3),
 (547, 3),
 (546, 3),
 (544, 3),
 (543, 3),
 (540, 3),
 (539, 3),
 (535, 3),
 (532, 3),
 (531, 3),
 (530, 3),
 (525, 3),
 (522, 3),
 (520, 3),
 (513, 3),
 (507, 3),
 (498, 3),
 (496, 3),
 (493, 3),
 (492, 3),
 (491, 3),
 (488, 3),
 (481, 3),
 (480, 3),
 (475, 3),
 (470, 3),
 (469, 3),
 (454, 3),
 (453, 3),
 (450, 3),
 (447, 3),
 (445, 3),
 (442, 3),
 (437, 3),
 (435, 3),
 (427, 3),
 (425, 3),
 (420, 3),
 (416, 3),
 (413, 3),
 (412, 3),
 (410, 3),
 (409, 3),
 (405, 3),
 (404, 3),
 (402, 3),
 (400, 3),
 (399, 3),
 (396, 3),
 (394, 3),
 (391, 3),
 (390, 3),
 (386, 3),
 (385, 3),
 (382, 3),
 (372, 3),
 (367, 3),
 (366, 3),
 (361, 3),
 (359, 3),
 (356, 3),
 (350, 3),
 (344, 3),
 (342, 3),
 (335, 3),
 (334, 3),
 (333, 3),
 (327, 3),
 (325, 3),
 (318, 3),
 (312, 3),
 (308, 3),
 (305, 3),
 (304, 3),
 (302, 3),
 (292, 3),
 (290, 3),
 (289, 3),
 (288, 3),
 (285, 3),
 (281, 3),
 (280, 3),
 (277, 3),
 (276, 3),
 (275, 3),
 (274, 3),
 (268, 3),
 (266, 3),
 (263, 3),
 (261, 3),
 (260, 3),
 (254, 3),
 (252, 3),
 (249, 3),
 (244, 3),
 (243, 3),
 (236, 3),
 (235, 3),
 (231, 3),
 (229, 3),
 (218, 3),
 (217, 3),
 (199, 3),
 (190, 3),
 (184, 3),
 (176, 3),
 (173, 3),
 (165, 3),
 (164, 3),
 (162, 3),
 (161, 3),
 (156, 3),
 (153, 3),
 (152, 3),
 (142, 3),
 (134, 3),
 (132, 3),
 (131, 3),
 (127, 3),
 (124, 3),
 (114, 3),
 (108, 3),
 (105, 3),
 (88, 3),
 (81, 3),
 (80, 3),
 (76, 3),
 (75, 3),
 (72, 3),
 (71, 3),
 (70, 3),
 (69, 3),
 (66, 3),
 (63, 3),
 (62, 3),
 (61, 3),
 (59, 3),
 (58, 3),
 (57, 3),
 (55, 3),
 (51, 3),
 (50, 3),
 (45, 3),
 (41, 3),
 (36, 3),
 (34, 3),
 (32, 3),
 (23, 3),
 (21, 3),
 (11, 3),
 (7, 3),
 (5, 3),
 (1613, 2),
 (1610, 2),
 (1606, 2),
 (1597, 2),
 (1596, 2),
 (1594, 2),
 (1583, 2),
 (1582, 2),
 (1581, 2),
 (1580, 2),
 (1566, 2),
 (1564, 2),
 (1561, 2),
 (1560, 2),
 (1554, 2),
 (1552, 2),
 (1547, 2),
 (1544, 2),
 (1539, 2),
 (1535, 2),
 (1530, 2),
 (1529, 2),
 (1517, 2),
 (1514, 2),
 (1503, 2),
 (1500, 2),
 (1498, 2),
 (1488, 2),
 (1485, 2),
 (1483, 2),
 (1481, 2),
 (1479, 2),
 (1478, 2),
 (1474, 2),
 (1473, 2),
 (1472, 2),
 (1471, 2),
 (1463, 2),
 (1461, 2),
 (1455, 2),
 (1444, 2),
 (1430, 2),
 (1418, 2),
 (1414, 2),
 (1411, 2),
 (1406, 2),
 (1398, 2),
 (1396, 2),
 ...]

In [31]:
%%sql
SELECT o.customer_id, SUM(oi.quantity) AS item_count
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
GROUP BY o.customer_id
ORDER BY item_count DESC;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(16, 19),
 (3, 19),
 (10, 18),
 (61, 17),
 (43, 17),
 (1, 17),
 (58, 16),
 (47, 16),
 (40, 16),
 (24, 16),
 (6, 16),
 (94, 15),
 (53, 15),
 (31, 15),
 (28, 15),
 (18, 15),
 (2, 15),
 (224, 14),
 (138, 14),
 (85, 14),
 (79, 14),
 (76, 14),
 (63, 14),
 (35, 14),
 (30, 14),
 (19, 14),
 (231, 13),
 (157, 13),
 (116, 13),
 (86, 13),
 (66, 13),
 (25, 13),
 (14, 13),
 (13, 13),
 (9, 13),
 (5, 13),
 (4, 13),
 (240, 12),
 (239, 12),
 (153, 12),
 (136, 12),
 (93, 12),
 (83, 12),
 (82, 12),
 (73, 12),
 (48, 12),
 (39, 12),
 (22, 12),
 (21, 12),
 (12, 12),
 (194, 11),
 (165, 11),
 (123, 11),
 (109, 11),
 (80, 11),
 (75, 11),
 (64, 11),
 (59, 11),
 (33, 11),
 (27, 11),
 (1374, 10),
 (1237, 10),
 (1203, 10),
 (176, 10),
 (135, 10),
 (120, 10),
 (104, 10),
 (50, 10),
 (46, 10),
 (42, 10),
 (38, 10),
 (37, 10),
 (32, 10),
 (26, 10),
 (20, 10),
 (17, 10),
 (15, 10),
 (1439, 9),
 (1426, 9),
 (1415, 9),
 (1382, 9),
 (1290, 9),
 (1184, 9),
 (1125, 9),
 (983, 9),
 (973, 9),
 (903, 9),
 (877, 9),
 (871, 9),
 (833, 9),
 (809, 9),
 (798, 9),
 (793, 9),
 (755, 9),
 (675, 9),
 (644, 9),
 (640, 9),
 (618, 9),
 (607, 9),
 (554, 9),
 (327, 9),
 (275, 9),
 (234, 9),
 (192, 9),
 (170, 9),
 (167, 9),
 (140, 9),
 (90, 9),
 (87, 9),
 (72, 9),
 (65, 9),
 (55, 9),
 (1442, 8),
 (1436, 8),
 (1433, 8),
 (1350, 8),
 (1311, 8),
 (1258, 8),
 (1229, 8),
 (1226, 8),
 (1225, 8),
 (1224, 8),
 (1201, 8),
 (1199, 8),
 (1188, 8),
 (1185, 8),
 (1165, 8),
 (1148, 8),
 (1132, 8),
 (1100, 8),
 (1093, 8),
 (1091, 8),
 (1078, 8),
 (1063, 8),
 (1057, 8),
 (1042, 8),
 (1040, 8),
 (1037, 8),
 (1031, 8),
 (1006, 8),
 (990, 8),
 (976, 8),
 (971, 8),
 (965, 8),
 (963, 8),
 (958, 8),
 (945, 8),
 (893, 8),
 (859, 8),
 (844, 8),
 (837, 8),
 (815, 8),
 (783, 8),
 (761, 8),
 (734, 8),
 (730, 8),
 (728, 8),
 (727, 8),
 (722, 8),
 (715, 8),
 (687, 8),
 (662, 8),
 (646, 8),
 (616, 8),
 (612, 8),
 (581, 8),
 (571, 8),
 (559, 8),
 (541, 8),
 (537, 8),
 (536, 8),
 (526, 8),
 (525, 8),
 (473, 8),
 (437, 8),
 (425, 8),
 (420, 8),
 (375, 8),
 (330, 8),
 (296, 8),
 (288, 8),
 (282, 8),
 (274, 8),
 (272, 8),
 (259, 8),
 (227, 8),
 (225, 8),
 (208, 8),
 (203, 8),
 (195, 8),
 (191, 8),
 (187, 8),
 (175, 8),
 (173, 8),
 (171, 8),
 (168, 8),
 (151, 8),
 (126, 8),
 (119, 8),
 (112, 8),
 (91, 8),
 (69, 8),
 (68, 8),
 (60, 8),
 (57, 8),
 (54, 8),
 (41, 8),
 (1443, 7),
 (1440, 7),
 (1438, 7),
 (1435, 7),
 (1421, 7),
 (1406, 7),
 (1391, 7),
 (1390, 7),
 (1368, 7),
 (1360, 7),
 (1358, 7),
 (1333, 7),
 (1328, 7),
 (1319, 7),
 (1314, 7),
 (1307, 7),
 (1296, 7),
 (1279, 7),
 (1273, 7),
 (1269, 7),
 (1251, 7),
 (1249, 7),
 (1247, 7),
 (1245, 7),
 (1217, 7),
 (1205, 7),
 (1158, 7),
 (1150, 7),
 (1147, 7),
 (1136, 7),
 (1135, 7),
 (1134, 7),
 (1131, 7),
 (1115, 7),
 (1113, 7),
 (1102, 7),
 (1081, 7),
 (1072, 7),
 (1046, 7),
 (1026, 7),
 (1020, 7),
 (991, 7),
 (989, 7),
 (985, 7),
 (953, 7),
 (931, 7),
 (920, 7),
 (919, 7),
 (904, 7),
 (888, 7),
 (886, 7),
 (885, 7),
 (883, 7),
 (878, 7),
 (873, 7),
 (865, 7),
 (853, 7),
 (819, 7),
 (813, 7),
 (810, 7),
 (799, 7),
 (778, 7),
 (774, 7),
 (754, 7),
 (738, 7),
 (726, 7),
 (702, 7),
 (690, 7),
 (681, 7),
 (672, 7),
 (670, 7),
 (657, 7),
 (645, 7),
 (627, 7),
 (619, 7),
 (615, 7),
 (597, 7),
 (595, 7),
 (594, 7),
 (583, 7),
 (578, 7),
 (577, 7),
 (568, 7),
 (555, 7),
 (538, 7),
 (529, 7),
 (519, 7),
 (495, 7),
 (492, 7),
 (480, 7),
 (469, 7),
 (464, 7),
 (453, 7),
 (450, 7),
 (428, 7),
 (417, 7),
 (400, 7),
 (383, 7),
 (380, 7),
 (374, 7),
 (352, 7),
 (350, 7),
 (344, 7),
 (337, 7),
 (331, 7),
 (298, 7),
 (295, 7),
 (287, 7),
 (279, 7),
 (276, 7),
 (269, 7),
 (263, 7),
 (238, 7),
 (226, 7),
 (220, 7),
 (218, 7),
 (217, 7),
 (214, 7),
 (213, 7),
 (207, 7),
 (201, 7),
 (197, 7),
 (182, 7),
 (172, 7),
 (169, 7),
 (163, 7),
 (159, 7),
 (124, 7),
 (110, 7),
 (105, 7),
 (99, 7),
 (92, 7),
 (84, 7),
 (81, 7),
 (70, 7),
 (62, 7),
 (52, 7),
 (44, 7),
 (11, 7),
 (1423, 6),
 (1410, 6),
 (1404, 6),
 (1401, 6),
 (1397, 6),
 (1395, 6),
 (1385, 6),
 (1384, 6),
 (1379, 6),
 (1378, 6),
 (1375, 6),
 (1373, 6),
 (1372, 6),
 (1367, 6),
 (1359, 6),
 (1354, 6),
 (1353, 6),
 (1349, 6),
 (1348, 6),
 (1304, 6),
 (1303, 6),
 (1301, 6),
 (1300, 6),
 (1298, 6),
 (1282, 6),
 (1278, 6),
 (1265, 6),
 (1261, 6),
 (1259, 6),
 (1257, 6),
 (1246, 6),
 (1233, 6),
 (1219, 6),
 (1216, 6),
 (1211, 6),
 (1209, 6),
 (1208, 6),
 (1206, 6),
 (1200, 6),
 (1197, 6),
 (1190, 6),
 (1183, 6),
 (1182, 6),
 (1172, 6),
 (1171, 6),
 (1169, 6),
 (1163, 6),
 (1153, 6),
 (1152, 6),
 (1145, 6),
 (1129, 6),
 (1128, 6),
 (1123, 6),
 (1118, 6),
 (1114, 6),
 (1108, 6),
 (1105, 6),
 (1097, 6),
 (1086, 6),
 (1083, 6),
 (1080, 6),
 (1071, 6),
 (1070, 6),
 (1067, 6),
 (1059, 6),
 (1056, 6),
 (1052, 6),
 (1048, 6),
 (1034, 6),
 (1029, 6),
 (1023, 6),
 (1021, 6),
 (1019, 6),
 (1018, 6),
 (1012, 6),
 (1007, 6),
 (995, 6),
 (988, 6),
 (987, 6),
 (986, 6),
 (977, 6),
 (966, 6),
 (961, 6),
 (960, 6),
 (951, 6),
 (939, 6),
 (922, 6),
 (916, 6),
 (908, 6),
 (895, 6),
 (887, 6),
 (880, 6),
 (870, 6),
 (866, 6),
 (840, 6),
 (839, 6),
 (836, 6),
 (826, 6),
 (814, 6),
 (802, 6),
 (801, 6),
 (787, 6),
 (748, 6),
 (737, 6),
 (732, 6),
 (723, 6),
 (713, 6),
 (711, 6),
 (706, 6),
 (694, 6),
 (691, 6),
 (679, 6),
 (669, 6),
 (667, 6),
 (665, 6),
 (661, 6),
 (651, 6),
 (648, 6),
 (647, 6),
 (643, 6),
 (637, 6),
 (629, 6),
 (625, 6),
 (609, 6),
 (603, 6),
 (600, 6),
 (584, 6),
 (569, 6),
 (564, 6),
 (560, 6),
 (547, 6),
 (546, 6),
 (531, 6),
 (530, 6),
 (521, 6),
 (517, 6),
 (506, 6),
 (502, 6),
 (500, 6),
 (499, 6),
 (486, 6),
 (485, 6),
 (481, 6),
 (479, 6),
 (459, 6),
 (447, 6),
 (444, 6),
 (443, 6),
 (441, 6),
 (434, 6),
 (431, 6),
 (421, 6),
 (413, 6),
 (411, 6),
 (410, 6),
 (395, 6),
 (386, 6),
 (384, 6),
 (367, 6),
 (361, 6),
 (358, 6),
 (333, 6),
 (326, 6),
 (316, 6),
 (315, 6),
 (314, 6),
 (313, 6),
 (310, 6),
 (299, 6),
 (292, 6),
 (262, 6),
 (260, 6),
 (256, 6),
 (252, 6),
 (206, 6),
 (205, 6),
 (204, 6),
 (198, 6),
 (196, 6),
 (190, 6),
 (162, 6),
 (146, 6),
 (115, 6),
 (113, 6),
 (88, 6),
 (77, 6),
 (56, 6),
 (51, 6),
 (45, 6),
 (36, 6),
 (34, 6),
 (29, 6),
 (7, 6),
 (1429, 5),
 (1418, 5),
 (1411, 5),
 (1409, 5),
 (1403, 5),
 (1399, 5),
 (1398, 5),
 (1386, 5),
 (1376, 5),
 (1362, 5),
 (1352, 5),
 (1351, 5),
 (1346, 5),
 (1343, 5),
 (1334, 5),
 (1329, 5),
 (1326, 5),
 (1323, 5),
 (1315, 5),
 (1305, 5),
 (1295, 5),
 (1287, 5),
 (1280, 5),
 (1274, 5),
 (1264, 5),
 (1240, 5),
 (1234, 5),
 (1232, 5),
 (1231, 5),
 (1227, 5),
 (1220, 5),
 (1215, 5),
 (1214, 5),
 (1213, 5),
 (1210, 5),
 (1194, 5),
 (1181, 5),
 (1175, 5),
 (1173, 5),
 (1162, 5),
 (1161, 5),
 (1160, 5),
 (1159, 5),
 (1151, 5),
 (1149, 5),
 (1144, 5),
 (1141, 5),
 (1137, 5),
 (1126, 5),
 (1122, 5),
 (1120, 5),
 (1112, 5),
 (1103, 5),
 (1101, 5),
 (1096, 5),
 (1090, 5),
 (1089, 5),
 (1088, 5),
 (1084, 5),
 (1075, 5),
 (1068, 5),
 (1066, 5),
 (1045, 5),
 (1043, 5),
 (1041, 5),
 (1033, 5),
 (1024, 5),
 (1010, 5),
 (1005, 5),
 (999, 5),
 (998, 5),
 (997, 5),
 (994, 5),
 (984, 5),
 (979, 5),
 (975, 5),
 (967, 5),
 (959, 5),
 (946, 5),
 (941, 5),
 (935, 5),
 (930, 5),
 (929, 5),
 (921, 5),
 (914, 5),
 (910, 5),
 (900, 5),
 (896, 5),
 (894, 5),
 (876, 5),
 (872, 5),
 (863, 5),
 (862, 5),
 (858, 5),
 (834, 5),
 (820, 5),
 (817, 5),
 (803, 5),
 (800, 5),
 (795, 5),
 (790, 5),
 (779, 5),
 (773, 5),
 (771, 5),
 (768, 5),
 (764, 5),
 (760, 5),
 (759, 5),
 (756, 5),
 (749, 5),
 (747, 5),
 (744, 5),
 (742, 5),
 (740, 5),
 (736, 5),
 (724, 5),
 (701, 5),
 (698, 5),
 (663, 5),
 (653, 5),
 (649, 5),
 (632, 5),
 (624, 5),
 (610, 5),
 (599, 5),
 (582, 5),
 (566, 5),
 (552, 5),
 (550, 5),
 (548, 5),
 (534, 5),
 (527, 5),
 (524, 5),
 (515, 5),
 (509, 5),
 (505, 5),
 (494, 5),
 (491, 5),
 (490, 5),
 (470, 5),
 (463, 5),
 (462, 5),
 (461, 5),
 (435, 5),
 (426, 5),
 (415, 5),
 (408, 5),
 (407, 5),
 (396, 5),
 (385, 5),
 (365, 5),
 (360, 5),
 (357, 5),
 (354, 5),
 (351, 5),
 (340, 5),
 (339, 5),
 (334, 5),
 (332, 5),
 (322, 5),
 (318, 5),
 (309, 5),
 (301, 5),
 (291, 5),
 (290, 5),
 (280, 5),
 (277, 5),
 (268, 5),
 (266, 5),
 (257, 5),
 (255, 5),
 (254, 5),
 (251, 5),
 (246, 5),
 (241, 5),
 (216, 5),
 (202, 5),
 (186, 5),
 (184, 5),
 (181, 5),
 (178, 5),
 (145, 5),
 (122, 5),
 (117, 5),
 (108, 5),
 (107, 5),
 (97, 5),
 (95, 5),
 (89, 5),
 (8, 5),
 (1441, 4),
 (1434, 4),
 (1431, 4),
 (1413, 4),
 (1408, 4),
 (1400, 4),
 (1381, 4),
 (1361, 4),
 (1341, 4),
 (1335, 4),
 (1332, 4),
 (1330, 4),
 (1324, 4),
 (1322, 4),
 (1321, 4),
 (1308, 4),
 (1306, 4),
 (1302, 4),
 (1299, 4),
 (1271, 4),
 (1268, 4),
 (1256, 4),
 (1254, 4),
 (1244, 4),
 (1243, 4),
 (1242, 4),
 (1238, 4),
 (1236, 4),
 (1230, 4),
 (1223, 4),
 (1222, 4),
 (1198, 4),
 (1193, 4),
 (1192, 4),
 (1189, 4),
 (1187, 4),
 (1179, 4),
 (1178, 4),
 (1138, 4),
 (1119, 4),
 (1109, 4),
 (1107, 4),
 (1104, 4),
 (1099, 4),
 (1087, 4),
 (1085, 4),
 (1074, 4),
 (1069, 4),
 (1062, 4),
 (1060, 4),
 (1054, 4),
 (1051, 4),
 (1047, 4),
 (1038, 4),
 (1028, 4),
 (1027, 4),
 (1003, 4),
 (1001, 4),
 (992, 4),
 (982, 4),
 (972, 4),
 (952, 4),
 (950, 4),
 (949, 4),
 (948, 4),
 (940, 4),
 (938, 4),
 (937, 4),
 (936, 4),
 (934, 4),
 (933, 4),
 (927, 4),
 (913, 4),
 (909, 4),
 (907, 4),
 (902, 4),
 (882, 4),
 (867, 4),
 (864, 4),
 (855, 4),
 (854, 4),
 (851, 4),
 (848, 4),
 (845, 4),
 (843, 4),
 (838, 4),
 (835, 4),
 (832, 4),
 (828, 4),
 (825, 4),
 (824, 4),
 (823, 4),
 (818, 4),
 (811, 4),
 (808, 4),
 (807, 4),
 (806, 4),
 (797, 4),
 (796, 4),
 (794, 4),
 (789, 4),
 (782, 4),
 (780, 4),
 (777, 4),
 (775, 4),
 (772, 4),
 (765, 4),
 (763, 4),
 (758, 4),
 (751, 4),
 (750, 4),
 (735, 4),
 (717, 4),
 (716, 4),
 (705, 4),
 (700, 4),
 (699, 4),
 (686, 4),
 (680, 4),
 (666, 4),
 (660, 4),
 (650, 4),
 (641, 4),
 (638, 4),
 (636, 4),
 (635, 4),
 (634, 4),
 (628, 4),
 (626, 4),
 (621, 4),
 (614, 4),
 (606, 4),
 (605, 4),
 (598, 4),
 (596, 4),
 (591, 4),
 (588, 4),
 (587, 4),
 (576, 4),
 (574, 4),
 (570, 4),
 (567, 4),
 (563, 4),
 (556, 4),
 (544, 4),
 (543, 4),
 (542, 4),
 (540, 4),
 (522, 4),
 (516, 4),
 (511, 4),
 (510, 4),
 (504, 4),
 (503, 4),
 (498, 4),
 (496, 4),
 (489, 4),
 (488, 4),
 (487, 4),
 (484, 4),
 (478, 4),
 (474, 4),
 (472, 4),
 (467, 4),
 (460, 4),
 (456, 4),
 (440, 4),
 (436, 4),
 (430, 4),
 (419, 4),
 (416, 4),
 (403, 4),
 (402, 4),
 (372, 4),
 (364, 4),
 (359, 4),
 (353, 4),
 (335, 4),
 (328, 4),
 (324, 4),
 (319, 4),
 (317, 4),
 (311, 4),
 (308, 4),
 (306, 4),
 (305, 4),
 (303, 4),
 (297, 4),
 (293, 4),
 (289, 4),
 (281, 4),
 (278, 4),
 (273, 4),
 (267, 4),
 (250, 4),
 (245, 4),
 (244, 4),
 (243, 4),
 (242, 4),
 (235, 4),
 (230, 4),
 (215, 4),
 (212, 4),
 (193, 4),
 (179, 4),
 (161, 4),
 (158, 4),
 (156, 4),
 (152, 4),
 (150, 4),
 (149, 4),
 (143, 4),
 (133, 4),
 (132, 4),
 (128, 4),
 (127, 4),
 (125, 4),
 (121, 4),
 (118, 4),
 (106, 4),
 (101, 4),
 (98, 4),
 (96, 4),
 (78, 4),
 (23, 4),
 (1444, 3),
 (1424, 3),
 (1422, 3),
 (1420, 3),
 (1412, 3),
 (1407, 3),
 (1405, 3),
 (1394, 3),
 (1392, 3),
 (1383, 3),
 (1377, 3),
 (1363, 3),
 (1356, 3),
 (1347, 3),
 (1345, 3),
 (1344, 3),
 (1339, 3),
 (1331, 3),
 (1318, 3),
 (1316, 3),
 (1312, 3),
 (1310, 3),
 (1294, 3),
 (1293, 3),
 (1291, 3),
 (1284, 3),
 (1266, 3),
 (1260, 3),
 (1255, 3),
 (1253, 3),
 (1250, 3),
 (1248, 3),
 (1235, 3),
 (1212, 3),
 (1204, 3),
 (1202, 3),
 (1195, 3),
 (1191, 3),
 (1180, 3),
 (1177, 3),
 (1174, 3),
 (1170, 3),
 (1164, 3),
 (1156, 3),
 (1155, 3),
 (1154, 3),
 ...]

In [35]:
%%sql
SELECT order_status, count(*) FROM orders
group by 1;

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(1, 62), (2, 63), (3, 45), (4, 1445)]

In [40]:
%%sql
SELECT order_status, order_date, required_date, shipped_date FROM orders
WHERE order_status IN (1,2,3);

   sqlite:///D:/Data_Analysis/project/sale/BikeStore.db
   sqlite:///D:/Data_Analysis/project/sale/bike_store.db
 * sqlite:///D:/Data_Analysis/project/sale/csv/BikeStore.db
Done.

[(3, '2016-02-11', '2016-02-11', 'NULL'),
 (3, '2016-02-16', '2016-02-16', 'NULL'),
 (3, '2016-04-04', '2016-04-04', 'NULL'),
 (3, '2016-04-20', '2016-04-20', 'NULL'),
 (3, '2016-05-27', '2016-05-27', 'NULL'),
 (3, '2016-05-30', '2016-05-30', 'NULL'),
 (3, '2016-06-10', '2016-06-10', 'NULL'),
 (3, '2016-08-03', '2016-08-03', 'NULL'),
 (3, '2016-08-03', '2016-08-03', 'NULL'),
 (3, '2016-08-05', '2016-08-05', 'NULL'),
 (3, '2016-08-23', '2016-08-23', 'NULL'),
 (3, '2016-09-01', '2016-09-01', 'NULL'),
 (3, '2016-11-12', '2016-11-12', 'NULL'),
 (3, '2016-12-04', '2016-12-04', 'NULL'),
 (3, '2016-12-09', '2016-12-09', 'NULL'),
 (3, '2017-02-05', '2017-02-05', 'NULL'),
 (3, '2017-02-15', '2017-02-15', 'NULL'),
 (3, '2017-02-27', '2017-02-27', 'NULL'),
 (3, '2017-03-15', '2017-03-15', 'NULL'),
 (3, '2017-04-01', '2017-04-01', 'NULL'),
 (3, '2017-05-13', '2017-05-13', 'NULL'),
 (3, '2017-06-02', '2017-06-02', 'NULL'),
 (3, '2017-06-10', '2017-06-10', 'NULL'),
 (3, '2017-07-18', '2017-07-18', 'NULL'),
 (3, '2017-07-23', '2017-07-23', 'NULL'),
 (3, '2017-08-08', '2017-08-08', 'NULL'),
 (3, '2017-08-18', '2017-08-18', 'NULL'),
 (3, '2017-08-19', '2017-08-19', 'NULL'),
 (3, '2017-08-23', '2017-08-23', 'NULL'),
 (3, '2017-10-12', '2017-10-12', 'NULL'),
 (3, '2017-11-07', '2017-11-07', 'NULL'),
 (3, '2017-11-21', '2017-11-21', 'NULL'),
 (3, '2018-02-26', '2018-02-26', 'NULL'),
 (2, '2018-04-01', '2018-04-01', 'NULL'),
 (2, '2018-04-01', '2018-04-01', 'NULL'),
 (1, '2018-04-01', '2018-04-01', 'NULL'),
 (1, '2018-04-01', '2018-04-01', 'NULL'),
 (1, '2018-04-02', '2018-04-02', 'NULL'),
 (2, '2018-04-02', '2018-04-02', 'NULL'),
 (2, '2018-04-02', '2018-04-02', 'NULL'),
 (2, '2018-04-02', '2018-04-02', 'NULL'),
 (1, '2018-04-03', '2018-04-03', 'NULL'),
 (2, '2018-04-03', '2018-04-03', 'NULL'),
 (1, '2018-04-03', '2018-04-03', 'NULL'),
 (2, '2018-04-03', '2018-04-03', 'NULL'),
 (1, '2018-04-04', '2018-04-04', 'NULL'),
 (1, '2018-04-04', '2018-04-04', 'NULL'),
 (2, '2018-04-04', '2018-04-04', 'NULL'),
 (2, '2018-04-05', '2018-04-05', 'NULL'),
 (2, '2018-04-05', '2018-04-05', 'NULL'),
 (1, '2018-04-06', '2018-04-06', 'NULL'),
 (2, '2018-04-06', '2018-04-06', 'NULL'),
 (1, '2018-04-06', '2018-04-06', 'NULL'),
 (2, '2018-04-06', '2018-04-06', 'NULL'),
 (2, '2018-04-06', '2018-04-06', 'NULL'),
 (1, '2018-04-06', '2018-04-06', 'NULL'),
 (2, '2018-04-06', '2018-04-06', 'NULL'),
 (2, '2018-04-07', '2018-04-07', 'NULL'),
 (2, '2018-04-08', '2018-04-08', 'NULL'),
 (1, '2018-04-08', '2018-04-08', 'NULL'),
 (1, '2018-04-08', '2018-04-08', 'NULL'),
 (2, '2018-04-08', '2018-04-08', 'NULL'),
 (2, '2018-04-08', '2018-04-08', 'NULL'),
 (1, '2018-04-09', '2018-04-09', 'NULL'),
 (2, '2018-04-09', '2018-04-09', 'NULL'),
 (1, '2018-04-09', '2018-04-09', 'NULL'),
 (1, '2018-04-09', '2018-04-09', 'NULL'),
 (2, '2018-04-10', '2018-04-10', 'NULL'),
 (2, '2018-04-10', '2018-04-10', 'NULL'),
 (1, '2018-04-10', '2018-04-10', 'NULL'),
 (2, '2018-04-11', '2018-04-11', 'NULL'),
 (1, '2018-04-11', '2018-04-11', 'NULL'),
 (1, '2018-04-11', '2018-04-11', 'NULL'),
 (2, '2018-04-11', '2018-04-11', 'NULL'),
 (2, '2018-04-11', '2018-04-11', 'NULL'),
 (1, '2018-04-12', '2018-04-12', 'NULL'),
 (1, '2018-04-12', '2018-04-12', 'NULL'),
 (1, '2018-04-12', '2018-04-12', 'NULL'),
 (1, '2018-04-12', '2018-04-12', 'NULL'),
 (2, '2018-04-12', '2018-04-12', 'NULL'),
 (2, '2018-04-12', '2018-04-12', 'NULL'),
 (2, '2018-04-12', '2018-04-12', 'NULL'),
 (1, '2018-04-12', '2018-04-12', 'NULL'),
 (1, '2018-04-12', '2018-04-12', 'NULL'),
 (1, '2018-04-13', '2018-04-13', 'NULL'),
 (1, '2018-04-13', '2018-04-13', 'NULL'),
 (2, '2018-04-13', '2018-04-13', 'NULL'),
 (2, '2018-04-13', '2018-04-13', 'NULL'),
 (2, '2018-04-14', '2018-04-14', 'NULL'),
 (2, '2018-04-14', '2018-04-14', 'NULL'),
 (2, '2018-04-14', '2018-04-14', 'NULL'),
 (1, '2018-04-15', '2018-04-15', 'NULL'),
 (2, '2018-04-15', '2018-04-15', 'NULL'),
 (1, '2018-04-15', '2018-04-15', 'NULL'),
 (1, '2018-04-16', '2018-04-16', 'NULL'),
 (2, '2018-04-16', '2018-04-16', 'NULL'),
 (2, '2018-04-16', '2018-04-16', 'NULL'),
 (1, '2018-04-16', '2018-04-16', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (2, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (1, '2018-04-17', '2018-04-17', 'NULL'),
 (2, '2018-04-18', '2018-04-18', 'NULL'),
 (1, '2018-04-18', '2018-04-18', 'NULL'),
 (1, '2018-04-18', '2018-04-18', 'NULL'),
 (2, '2018-04-18', '2018-04-18', 'NULL'),
 (2, '2018-04-19', '2018-04-19', 'NULL'),
 (1, '2018-04-19', '2018-04-19', 'NULL'),
 (2, '2018-04-20', '2018-04-20', 'NULL'),
 (1, '2018-04-20', '2018-04-20', 'NULL'),
 (2, '2018-04-20', '2018-04-20', 'NULL'),
 (1, '2018-04-20', '2018-04-20', 'NULL'),
 (2, '2018-04-20', '2018-04-20', 'NULL'),
 (1, '2018-04-21', '2018-04-21', 'NULL'),
 (2, '2018-04-21', '2018-04-21', 'NULL'),
 (1, '2018-04-21', '2018-04-21', 'NULL'),
 (2, '2018-04-21', '2018-04-21', 'NULL'),
 (2, '2018-04-21', '2018-04-21', 'NULL'),
 (2, '2018-04-22', '2018-04-22', 'NULL'),
 (2, '2018-04-22', '2018-04-22', 'NULL'),
 (1, '2018-04-22', '2018-04-22', 'NULL'),
 (1, '2018-04-22', '2018-04-22', 'NULL'),
 (2, '2018-04-23', '2018-04-23', 'NULL'),
 (1, '2018-04-23', '2018-04-23', 'NULL'),
 (2, '2018-04-23', '2018-04-23', 'NULL'),
 (2, '2018-04-23', '2018-04-23', 'NULL'),
 (1, '2018-04-23', '2018-04-23', 'NULL'),
 (2, '2018-04-23', '2018-04-23', 'NULL'),
 (2, '2018-04-24', '2018-04-24', 'NULL'),
 (2, '2018-04-24', '2018-04-24', 'NULL'),
 (2, '2018-04-25', '2018-04-25', 'NULL'),
 (1, '2018-04-25', '2018-04-25', 'NULL'),
 (1, '2018-04-25', '2018-04-25', 'NULL'),
 (2, '2018-04-26', '2018-04-26', 'NULL'),
 (1, '2018-04-26', '2018-04-26', 'NULL'),
 (1, '2018-04-26', '2018-04-26', 'NULL'),
 (2, '2018-04-26', '2018-04-26', 'NULL'),
 (1, '2018-04-26', '2018-04-26', 'NULL'),
 (2, '2018-04-27', '2018-04-27', 'NULL'),
 (1, '2018-04-27', '2018-04-27', 'NULL'),
 (2, '2018-04-27', '2018-04-27', 'NULL'),
 (2, '2018-04-27', '2018-04-27', 'NULL'),
 (1, '2018-04-27', '2018-04-27', 'NULL'),
 (1, '2018-04-28', '2018-04-28', 'NULL'),
 (2, '2018-04-28', '2018-04-28', 'NULL'),
 (2, '2018-04-28', '2018-04-28', 'NULL'),
 (1, '2018-04-28', '2018-04-28', 'NULL'),
 (2, '2018-04-29', '2018-04-29', 'NULL'),
 (1, '2018-04-29', '2018-04-29', 'NULL'),
 (1, '2018-04-29', '2018-04-29', 'NULL'),
 (1, '2018-04-29', '2018-04-29', 'NULL'),
 (1, '2018-04-30', '2018-04-30', 'NULL'),
 (2, '2018-04-30', '2018-04-30', 'NULL'),
 (3, '2018-06-17', '2018-06-17', 'NULL'),
 (3, '2018-07-01', '2018-07-01', 'NULL'),
 (3, '2018-07-10', '2018-07-10', 'NULL'),
 (3, '2018-07-11', '2018-07-11', 'NULL'),
 (3, '2018-07-12', '2018-07-12', 'NULL'),
 (3, '2018-08-23', '2018-08-23', 'NULL'),
 (3, '2018-08-25', '2018-08-25', 'NULL'),
 (3, '2018-09-06', '2018-09-06', 'NULL'),
 (3, '2018-10-21', '2018-10-21', 'NULL'),
 (3, '2018-11-18', '2018-11-18', 'NULL'),
 (3, '2018-11-28', '2018-11-28', 'NULL'),
 (3, '2018-12-28', '2018-12-28', 'NULL')]